import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface AchievementData {
  key: string;
  name: string;
  namePt: string;
  description: string;
  descriptionPt: string;
  icon: string;
  category: string;
  thresholdValue?: number;
  xpReward: number;
}

const achievements: AchievementData[] = [
  // Categoria: Consistência
  {
    key: 'first_workout',
    name: 'First Step',
    namePt: 'Primeiro Passo',
    description: 'Complete your first workout',
    descriptionPt: 'Complete seu primeiro treino',
    icon: 'trophy',
    category: 'consistency',
    thresholdValue: 1,
    xpReward: 50,
  },
  {
    key: 'sessions_5',
    name: 'Warming Up',
    namePt: 'Aquecendo',
    description: 'Complete 5 workouts',
    descriptionPt: 'Complete 5 treinos',
    icon: 'fire',
    category: 'consistency',
    thresholdValue: 5,
    xpReward: 100,
  },
  {
    key: 'sessions_10',
    name: 'Dedicated',
    namePt: 'Dedicado',
    description: 'Complete 10 workouts',
    descriptionPt: 'Complete 10 treinos',
    icon: 'fire',
    category: 'consistency',
    thresholdValue: 10,
    xpReward: 150,
  },
  {
    key: 'sessions_25',
    name: 'Consistent',
    namePt: 'Consistente',
    description: 'Complete 25 workouts',
    descriptionPt: 'Complete 25 treinos',
    icon: 'star',
    category: 'consistency',
    thresholdValue: 25,
    xpReward: 250,
  },
  {
    key: 'sessions_50',
    name: 'Machine',
    namePt: 'Máquina',
    description: 'Complete 50 workouts',
    descriptionPt: 'Complete 50 treinos',
    icon: 'crown',
    category: 'consistency',
    thresholdValue: 50,
    xpReward: 500,
  },
  {
    key: 'sessions_100',
    name: 'Centurion',
    namePt: 'Centurião',
    description: 'Complete 100 workouts',
    descriptionPt: 'Complete 100 treinos',
    icon: 'crown',
    category: 'consistency',
    thresholdValue: 100,
    xpReward: 1000,
  },
  {
    key: 'sessions_250',
    name: 'Legend',
    namePt: 'Lenda',
    description: 'Complete 250 workouts',
    descriptionPt: 'Complete 250 treinos',
    icon: 'medal',
    category: 'consistency',
    thresholdValue: 250,
    xpReward: 2500,
  },
  {
    key: 'streak_3',
    name: 'Three is Too Many',
    namePt: 'Três é Demais',
    description: 'Train 3 consecutive days',
    descriptionPt: 'Treine 3 dias seguidos',
    icon: 'fire',
    category: 'consistency',
    thresholdValue: 3,
    xpReward: 75,
  },
  {
    key: 'streak_7',
    name: 'Week of Fire',
    namePt: 'Semana de Fogo',
    description: 'Train 7 consecutive days',
    descriptionPt: 'Treine 7 dias seguidos',
    icon: 'fire',
    category: 'consistency',
    thresholdValue: 7,
    xpReward: 150,
  },
  {
    key: 'streak_14',
    name: 'Two Weeks Strong',
    namePt: 'Duas Semanas Forte',
    description: 'Train 14 consecutive days',
    descriptionPt: 'Treine 14 dias seguidos',
    icon: 'fire',
    category: 'consistency',
    thresholdValue: 14,
    xpReward: 300,
  },
  {
    key: 'streak_30',
    name: 'Unstoppable Month',
    namePt: 'Mês Imparável',
    description: 'Train 30 consecutive days',
    descriptionPt: 'Treine 30 dias seguidos',
    icon: 'fire',
    category: 'consistency',
    thresholdValue: 30,
    xpReward: 750,
  },
  {
    key: 'streak_90',
    name: 'Iron Quarter',
    namePt: 'Trimestre de Ferro',
    description: 'Train 90 consecutive days',
    descriptionPt: 'Treine 90 dias seguidos',
    icon: 'diamond',
    category: 'consistency',
    thresholdValue: 90,
    xpReward: 2000,
  },
  {
    key: 'weekend_warrior',
    name: 'Weekend Warrior',
    namePt: 'Guerreiro de Fim de Semana',
    description: 'Train on a Saturday and Sunday',
    descriptionPt: 'Treine em um sábado e domingo',
    icon: 'sword',
    category: 'consistency',
    xpReward: 100,
  },
  {
    key: 'early_bird',
    name: 'Early Bird',
    namePt: 'Madrugador',
    description: 'Start a workout before 7 AM',
    descriptionPt: 'Comece um treino antes das 7h',
    icon: 'sunrise',
    category: 'consistency',
    xpReward: 75,
  },
  {
    key: 'night_owl',
    name: 'Night Owl',
    namePt: 'Coruja',
    description: 'Start a workout after 10 PM',
    descriptionPt: 'Comece um treino depois das 22h',
    icon: 'moon',
    category: 'consistency',
    xpReward: 75,
  },

  // Categoria: Força
  {
    key: 'first_pr',
    name: 'First Record',
    namePt: 'Primeiro Record',
    description: 'Break your first personal record',
    descriptionPt: 'Quebre seu primeiro record pessoal',
    icon: 'trophy',
    category: 'strength',
    thresholdValue: 1,
    xpReward: 100,
  },
  {
    key: 'pr_5',
    name: 'Breaking Limits',
    namePt: 'Quebrando Limites',
    description: 'Break 5 personal records',
    descriptionPt: 'Quebre 5 records pessoais',
    icon: 'muscle',
    category: 'strength',
    thresholdValue: 5,
    xpReward: 200,
  },
  {
    key: 'pr_15',
    name: 'Record Machine',
    namePt: 'Máquina de Records',
    description: 'Break 15 personal records',
    descriptionPt: 'Quebre 15 records pessoais',
    icon: 'lightning',
    category: 'strength',
    thresholdValue: 15,
    xpReward: 400,
  },
  {
    key: 'pr_50',
    name: 'Unstoppable',
    namePt: 'Imparável',
    description: 'Break 50 personal records',
    descriptionPt: 'Quebre 50 records pessoais',
    icon: 'fire',
    category: 'strength',
    thresholdValue: 50,
    xpReward: 1000,
  },
  {
    key: 'volume_1000',
    name: 'First Ton',
    namePt: 'Primeira Tonelada',
    description: 'Lift 1,000 kg of total volume in a session',
    descriptionPt: 'Levante 1.000 kg de volume total em uma sessão',
    icon: 'weight',
    category: 'strength',
    thresholdValue: 1000,
    xpReward: 100,
  },
  {
    key: 'volume_5000',
    name: '5 Tons',
    namePt: '5 Toneladas',
    description: 'Lift 5,000 kg of total volume in a session',
    descriptionPt: 'Levante 5.000 kg de volume total em uma sessão',
    icon: 'weight',
    category: 'strength',
    thresholdValue: 5000,
    xpReward: 250,
  },
  {
    key: 'volume_10000',
    name: '10 Tons',
    namePt: '10 Toneladas',
    description: 'Lift 10,000 kg of total volume in a session',
    descriptionPt: 'Levante 10.000 kg de volume total em uma sessão',
    icon: 'weight',
    category: 'strength',
    thresholdValue: 10000,
    xpReward: 500,
  },
  {
    key: 'total_volume_100k',
    name: '100k KG',
    namePt: '100 Mil KG',
    description: 'Reach 100,000 kg of lifetime total volume',
    descriptionPt: 'Alcance 100.000 kg de volume total acumulado',
    icon: 'mountain',
    category: 'strength',
    thresholdValue: 100000,
    xpReward: 500,
  },
  {
    key: 'total_volume_1m',
    name: 'One Million',
    namePt: 'Um Milhão',
    description: 'Reach 1,000,000 kg of lifetime total volume',
    descriptionPt: 'Alcance 1.000.000 kg de volume total acumulado',
    icon: 'star',
    category: 'strength',
    thresholdValue: 1000000,
    xpReward: 2000,
  },
  {
    key: 'all_muscle_groups',
    name: 'Full Body',
    namePt: 'Corpo Completo',
    description: 'Train all muscle groups in a week',
    descriptionPt: 'Treine todos os grupos musculares em uma semana',
    icon: 'dna',
    category: 'strength',
    thresholdValue: 7,
    xpReward: 200,
  },

  // Categoria: Avaliação
  {
    key: 'first_assessment',
    name: 'Baseline',
    namePt: 'Linha de Base',
    description: 'Record your first physical assessment',
    descriptionPt: 'Registre sua primeira avaliação física',
    icon: 'ruler',
    category: 'assessment',
    thresholdValue: 1,
    xpReward: 50,
  },
  {
    key: 'assessments_3',
    name: 'Tracking',
    namePt: 'Acompanhando',
    description: 'Record 3 physical assessments',
    descriptionPt: 'Registre 3 avaliações físicas',
    icon: 'chart',
    category: 'assessment',
    thresholdValue: 3,
    xpReward: 100,
  },
  {
    key: 'assessments_6',
    name: 'Constant Monitoring',
    namePt: 'Monitoramento Constante',
    description: 'Record 6 physical assessments',
    descriptionPt: 'Registre 6 avaliações físicas',
    icon: 'trending',
    category: 'assessment',
    thresholdValue: 6,
    xpReward: 200,
  },
  {
    key: 'assessments_12',
    name: 'Year of Data',
    namePt: 'Um Ano de Dados',
    description: 'Record 12 physical assessments',
    descriptionPt: 'Registre 12 avaliações físicas',
    icon: 'calendar',
    category: 'assessment',
    thresholdValue: 12,
    xpReward: 500,
  },
  {
    key: 'weight_loss_5',
    name: '-5 KG',
    namePt: '-5 KG',
    description: 'Lose 5 kg of body weight',
    descriptionPt: 'Perca 5 kg de peso corporal',
    icon: 'arrow_down',
    category: 'assessment',
    thresholdValue: -5,
    xpReward: 300,
  },
  {
    key: 'weight_gain_5',
    name: '+5 KG',
    namePt: '+5 KG',
    description: 'Gain 5 kg of body weight',
    descriptionPt: 'Ganhe 5 kg de peso corporal',
    icon: 'arrow_up',
    category: 'assessment',
    thresholdValue: 5,
    xpReward: 300,
  },
  {
    key: 'bf_decrease_3',
    name: 'Definition',
    namePt: 'Definição',
    description: 'Reduce 3% body fat',
    descriptionPt: 'Reduza 3% de gordura corporal',
    icon: 'target',
    category: 'assessment',
    thresholdValue: -3,
    xpReward: 400,
  },
  {
    key: 'arm_growth_2',
    name: 'Growing Arms',
    namePt: 'Braços Crescendo',
    description: 'Increase 2 cm in arm measurement',
    descriptionPt: 'Aumente 2 cm na medida do braço',
    icon: 'muscle',
    category: 'assessment',
    thresholdValue: 2,
    xpReward: 200,
  },

  // Categoria: Marcos
  {
    key: 'account_7d',
    name: 'One Week',
    namePt: 'Uma Semana',
    description: '7 days since registration',
    descriptionPt: '7 dias desde o cadastro',
    icon: 'calendar',
    category: 'milestone',
    thresholdValue: 7,
    xpReward: 25,
  },
  {
    key: 'account_30d',
    name: 'One Month',
    namePt: 'Um Mês',
    description: '30 days since registration',
    descriptionPt: '30 dias desde o cadastro',
    icon: 'calendar',
    category: 'milestone',
    thresholdValue: 30,
    xpReward: 50,
  },
  {
    key: 'account_90d',
    name: 'Three Months',
    namePt: 'Três Meses',
    description: '90 days since registration',
    descriptionPt: '90 dias desde o cadastro',
    icon: 'calendar',
    category: 'milestone',
    thresholdValue: 90,
    xpReward: 100,
  },
  {
    key: 'account_365d',
    name: 'One Year',
    namePt: 'Um Ano',
    description: '365 days since registration',
    descriptionPt: '365 dias desde o cadastro',
    icon: 'cake',
    category: 'milestone',
    thresholdValue: 365,
    xpReward: 500,
  },
  {
    key: 'first_custom_exercise',
    name: 'Creative',
    namePt: 'Criativo',
    description: 'Create your first custom exercise',
    descriptionPt: 'Crie seu primeiro exercício customizado',
    icon: 'pencil',
    category: 'milestone',
    thresholdValue: 1,
    xpReward: 50,
  },
  {
    key: 'first_ai_workout',
    name: 'Future Workout',
    namePt: 'Treino do Futuro',
    description: 'Use AI to generate a workout',
    descriptionPt: 'Use a IA para gerar um treino',
    icon: 'robot',
    category: 'milestone',
    thresholdValue: 1,
    xpReward: 75,
  },
  {
    key: 'workout_variety_5',
    name: 'Variety',
    namePt: 'Variedade',
    description: 'Create 5 different workouts',
    descriptionPt: 'Crie 5 treinos diferentes',
    icon: 'palette',
    category: 'milestone',
    thresholdValue: 5,
    xpReward: 100,
  },
];

export async function seedAchievements() {
  console.log('🏆 Seeding achievements...');

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: {
        name: achievement.name,
        namePt: achievement.namePt,
        description: achievement.description,
        descriptionPt: achievement.descriptionPt,
        icon: achievement.icon,
        category: achievement.category,
        thresholdValue: achievement.thresholdValue,
        xpReward: achievement.xpReward,
      },
      create: achievement,
    });
  }

  const count = await prisma.achievement.count();
  console.log(`✅ ${count} achievements seeded`);
}
